### ISSUE TITLE
Curious, why remove `mmlu` and `drop` from the list of datasets?

### ISSUE THREAD

**Issue by vgoklani** [jondurbin/bagel#5]
Hey there,

Curious, why did you remove `mmlu` and `drop`? 

Are they considered low-quality datasets for training? Or do you want to avoid any potential leakage with the evaluation frameworks?

Thanks!

**Comment by jon-convai** [comment]
MMLU doesn't really seem to add much to the model's abilities, and most people don't use LLMs for multiple choice anyway, so it seems like it's just wasted compute cycles.

DROP is somewhat more helpful, for RAG, but the answers are extremely short.  I also include ROPES, airoboros context-obedient items, and squadv2 train, so this particular dataset is a bit redundant.
